# Generated by Django 3.1 on 2020-10-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock_fort_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
