# Generated by Django 3.1 on 2020-10-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock_fort_backend', '0002_auto_20201018_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tID',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
